### ISSUE TITLE
Caching a value that should be re-computable

### ISSUE THREAD

**Issue by tgymnich** [EnzymeAD/Enzyme#1018]
https://fwd.gymni.ch/tuvWQ9

**Comment by wsmoses** [comment]
https://fwd.gymni.ch/403Ty2

It's caching the subcall (of normal_pdf_, because it doesn't know it is legal and cost-effieicnt to do so. E.g. it could've been fib!

Adding O1 (and thus readnone/nounwind/etc), avoid the cache: https://fwd.gymni.ch/oHaovR
