### ISSUE TITLE
compilation errors w/ llvm 16

### ISSUE THREAD

**Issue by samuelpmish** [EnzymeAD/Enzyme#1044]
Hi, 

I was trying to build enzyme against llvm 16 to see if some of the new `clang-repl` features were interoperable with enzyme, but I'm seeing quite a few compilation errors. I've attached a log file with the compilation errors when building Enzyme (0f4c968af4cee6efec40fa22276816aef24ae0c6) configured with

```
cmake . -Bbuild -DLLVM_DIR=/home/sam/code/llvm-16/build/lib/cmake/llvm -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/home/sam/code/llvm-16/build/bin/clang++
```

where llvm 16.0 was built with the following options:

```
cmake -G Ninja -DLLVM_TARGETS_TO_BUILD="host" -DLLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra" -DLLVM_ENABLE_PLUGINS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi"
```

--------

[output.txt](https://github.com/EnzymeAD/Enzyme/files/11036566/output.txt)

**Comment by wsmoses** [comment]
@tgymnich this looks like an llvm optional issue

Can we add a #if llvmver >= 16
using Optional=std::optional
#endif

And see if that fixes?

**Comment by samuelpmish** [comment]
follow-up question: does Enzyme work with LLVM 15? Since 16 wasn't working, I tried 15 instead, but now I'm getting an error from lld when building:

```
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/main.dir/link.txt --verbose=1
/path/to/my_project/build/TPL_llvm-prefix/src/TPL_llvm-build/bin/clang++ -O2 -g -DNDEBUG -arch arm64 -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Wl,
-search_paths_first -Wl,-headerpad_max_install_names -L/opt/homebrew/opt/ruby/lib -fuse-ld=lld 
-Wl, --lto-legacy-pass-manager 
-Wl, -mllvm=-load=/path/to/my_project/TPL/Enzyme/enzyme/build/Enzyme/LLDEnzyme-15.dylib CMakeFiles/main.dir/tests/main.cpp.o -o main
ld64.lld: error: unknown argument '--lto-legacy-pass-manager'
ld64.lld: error: unknown argument '-mllvm=-load=/Users/sam/code/serac/TPL/Enzyme/enzyme/build/Enzyme/LLDEnzyme-15.dylib'
```

**Comment by samuelpmish** [comment]
> Since 16 wasn't working, I tried 15 instead, but now I'm getting an error from lld when building: ...

It looks like this issue was caused by a bad installation step of llvm, so some old files were leftover. Building Enzyme against a clean llvm 15.0.7 seems to be working after all.

**Comment by wsmoses** [comment]
You should drop the `-flegacy-pass-manager` and also add  `-fpass-plugin=/home/sam/code/Enzyme/enzyme/build/Enzyme/ClangEnzyme-15.so'

**Comment by stepasite** [comment]
Hi Guys,
I did fork the repo and did a bunch of code replacements to try if it builds with llvm 16:

https://github.com/stepasite/Enzyme/pull/1

Unfortunately, it seems some parts of legacy pass manager were deleted in llvm 16:

https://github.com/llvm/llvm-project/commit/7ae6838defb21737963b1dd8ff9de7e87052c74f

which means `EnzymePassLoader` does not compile. My knowledge does not allow me to write a new pass builder so I am wondering if there would possibly exist some workaround to that issue.

Anyway, if you look into main branch, you will see `PassManagerBuilder` is already gone.

Thanks in advance for any hint,
Pavel

**Comment by wsmoses** [comment]
@stepasite we can probably just condition on LLVM version and not compile the old PM pieces on newer LLVM versions.

Would you mind making a PR with your replacements to the main branch?

The only comment I have immediately is that we'll need to version check those fixes (e.g. only if LLVM_VERSION_MAJOR >= 16 else ...existing code... )

**Comment by stepasite** [comment]
> @stepasite we can probably just condition on LLVM version and not compile the old PM pieces on newer LLVM versions.
> 
> Would you mind making a PR with your replacements to the main branch?
> 
> The only comment I have immediately is that we'll need to version check those fixes (e.g. only if LLVM_VERSION_MAJOR >= 16 else ...existing code... )

Ok, I will try to rule out the old pass manager to see if that works. If it will, I would then prepare a PR with proper ifdefs on gcc version to see if all your tests pass.

**Comment by stepasite** [comment]
> @stepasite we can probably just condition on LLVM version and not compile the old PM pieces on newer LLVM versions.
> 
> Would you mind making a PR with your replacements to the main branch?
> 
> The only comment I have immediately is that we'll need to version check those fixes (e.g. only if LLVM_VERSION_MAJOR >= 16 else ...existing code... )

I created a PR: https://github.com/EnzymeAD/Enzyme/pull/1106

I can only state it compiles with llvm 16.0.1 on Ubuntu.

I was not sure about the way how you want to deal with std::optional so I did pre-compiler condition everywhere rather than trying to provide some wrapper.
