### ISSUE TITLE
Support for IFX

### ISSUE THREAD

**Issue by l90lpa** [EnzymeAD/Enzyme#1056]
This is a proposal to support the llvm-based Intel Fortran compiler, IFX.

IFX is closed source, but free to use. At the time of writing, there are currently 2 versions, 2022.2.1, and 2023.0.0. Both of these are based on LLVM 15.  

To support IFX, Enzyme needs to be able to handle the IFX intrinsic `llvm.intel.subscript.*`, and calls to the compiler's runtime libraries. Given that the runtime libraries are large, and that the catalyst for this proposal is to use Enzyme on [MOM6](https://github.com/mom-ocean/MOM6) (an open-source ocean model), I suggest the initial set of runtime library functions that Enzyme should support are those present in MOM6, under IFX, which is ~50 unique functions (many of which will likely be considered inactive).

**Comment by ludgerpaehler** [comment]
@l90lpa hey Liam, absolutely love to see work on better support for Fortran :)) Could you maybe also check, and potentially open another issue, which MPI functions MOM6 uses so that we can also see if we need to add handling for further MPI primitives?

**Comment by wsmoses** [comment]
Definitely, please feel free to make a PR or write the functions in this issue
