### ISSUE TITLE
Add support IFX intrinsic 'llvm.intel.subscript'

### ISSUE THREAD

**Issue by l90lpa** [EnzymeAD/Enzyme#1120]
The intrinsic, `llvm.intel.subscript`, is used for accessing multidimensional arrays. For example, in Fortran we might have,

```fortran
    ...
c   where, lb*, and ub*, are the lower and upper bounds of their respective axis
    real(kind=4) :: A(lb1:ub1, lb2:ub2)
    A(i, j) = 1.0
```
 
which when transformed to LLVM IR, through IFX, can be represented as 2 calls to ``llvm.intel.subscript`` intrinsic.

 
```llvm
    ; where %base = &A(lb1, lb2) i.e. the address of the first element
    ;       %stride2 = (ub1 - lb1 + 1) * sizeof(float)
    ;       %stride1 = sizeof(float)
    %base1 = call float* @llvm.intel.subscript...(i8 1, i64 %lb2, i64 %stride2, float* elementtype(float) %base, i32 %j)

    %ptr = call float* @llvm.intel.subscript...(i8 0, i64 %lb1, i64 %stride1, float* elementtype(float) %base1, i32 %i)

    store float 1.0, float* %ptr, align 4
 ```
 
 The offset calulated by the intrinsic is done as follows,
 
 `offset = (lowerBound - index)*stride`
 `offsetPtr = basePtr + offset`
 
 
Note, address calculation does not feature the first parameter. This parameter is the axis (zero based), and is used by some Intel extensions, and in Intel loop optimization.

**Comment by wsmoses** [comment]
Looks like it should effectively be similar to a GEP instruction, if you want to take a stab at.
