### ISSUE TITLE
Compilation error in test code in compiler explorer

### ISSUE THREAD

**Issue by fourlex** [EnzymeAD/Enzyme#1220]
Hi, I try to run [this test](https://github.com/EnzymeAD/Enzyme/blob/main/enzyme/test/Integration/ReverseMode/virtualshadow3.cpp) in compiler explorer (https://fwd.gymni.ch/FsCzds) but the compilation fails.  I think #316 #890 are related. Thanks!

**Comment by wsmoses** [comment]
Yeah that one requires a higher optimization level (O2 in the test at least). We should probably upgrade it to be able to take a lower one as well, but FYI.

**Comment by fourlex** [comment]
It works if I put -O2 in compiler options box, thank you!
