### ISSUE TITLE
`__enzyme_allocation_like` fails to detect null pointer argument index

### ISSUE THREAD

**Issue by pengmai** [EnzymeAD/Enzyme#1321]
**Context**: [When registering a custom allocator via `__enzyme_allocation_like` as a global array, the second element is the index of the argument for the size of the memory allocation](https://github.com/EnzymeAD/Enzyme/issues/930#issuecomment-1334502012). This element must be an integer casted to a pointer.

If this index is 0, many frontends (including `clang` and `mlir-translate`) will emit a `ConstantPointerNull` instead of a `ConstantInt` in the array. This causes `preserve-nvvm` to fail to detect the metadata, which triggers a crash.

Is there a known workaround? If not, I believe the fix should be pretty simple and I'm happy to submit a PR.

**Comment by wsmoses** [comment]
Not that I'm aware of, fix is welcome!
