### ISSUE TITLE
`__enzyme_autodiff` w/ `enzyme_out` + pass by reference crashes

### ISSUE THREAD

**Issue by samuelpmishLLNL** [EnzymeAD/Enzyme#1349]
A function that takes arguments by reference

```cpp
double foo(const double & a, const double & x) { return sin(a) * x; }
```

works nicely with `__enzyme_fwddiff()` directly (although the requirement prepending of &'s when passing arguments by reference is counterintuitive C++)

```cpp
double a = 1.3;
double x = 1.9;
double dx = 2.3;
double output = __enzyme_fwddiff<double>((void*)foo, enzyme_const, &a, enzyme_dup, &x, &dx);
```

but trying to use `enzyme_out` with `__enzyme_autodiff` on a by-reference argument crashes clang 16:

```cpp
// crashes compiler
output = __enzyme_autodiff<double>((void*)foo, enzyme_const, &a, enzyme_out, &x);
```

link to example: https://fwd.gymni.ch/dcyWre

---

After playing with it a bit, I think the reason is that there's a type mismatch between the manually specified return type (`double`) and the argument marked with `enzyme_out` (`double &`), but it's difficult to discover that from the crash report. Also, specifying `double&` as the explicit template argument doesn't fix it. In conventional C++, a function that returning `double &` can assign to a `double` by implicit conversion, which makes it surprising when this isn't allowed (and crashes without indicating to the user what went wrong).

Is there any case where `enzyme_out` can be used in `__enzyme_autodiff()` on a reference argument (or pointer, rvalue ref -- these cases also crash)? Or does it only work for arguments passed by-value?

Using `enzyme_dupnoneed` or `enzyme_dup` with a separate output variable also works when dealing with functions with reference arguments.

```cpp
  double wx;
  __enzyme_autodiff<void>((void*)foo, enzyme_const, &a, enzyme_dup, &x, &wx);
```

**Comment by wsmoses** [comment]
Yeah, Pointer-like (or reference) variables don't work with enzyme_out, only pass by value data works with enzyme_out.
