### ISSUE TITLE
No ClangEnzyme-<version>.so library created when compiling the code on MacOSX

### ISSUE THREAD

**Issue by acuoci** [EnzymeAD/Enzyme#1368]
The compilation does not produce a `ClangEnzyme-<version>.so` file, but only a `ClangEnzyme-<version>.dylib` file:

```
cd /path/to/Enzyme/enzyme
mkdir build && cd build
cmake -G Ninja .. -DLLVM_DIR=/path/to/llvm/lib/cmake/llvm
ninja
```

The same happens even if the installation is done via brew:

`brew install enzyme`

**Comment by ludgerpaehler** [comment]
You are on MacOS right? The right file format on macOS is a .dylib - the functionality stays the same though :)

**Comment by acuoci** [comment]
Thank you very much. Unfortunately when I try to compile the Getting started example (described here https://enzyme.mit.edu/getting_started/UsingEnzyme/), I have a new issue:

```
clang test.c -fplugin=/mypath/Enzyme/ClangEnzyme-16.dylib -o a.exe

test.c:2:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
```

If I remove the `#include <stdio.h>` line and the corresponding `printf` line, the code is properly compiled.

**Comment by tgymnich** [comment]
What kind of clang are you using (AppleClang, homebrew clang, self compiled clang)?

did you install the macOS command line tools or Xcode?

**Comment by acuoci** [comment]
I am using homebrew clang
`/opt/homebrew/opt/llvm/bin/clang`

I am sorry, but I am not very familiar with the macOS environment.
If I type: `xcode-select -p`, the result is:
`/Applications/Xcode.app/Contents/Developer`

Thank you very much for your help.

**Comment by tgymnich** [comment]
I think there might be something wrong with your Xcode install or the command line tools. Some users had success with running `xcode-select --install`. It could also help to open Xcode to see if there is some kind of install dialogue popping up and follow the instructions in that case.

**Comment by acuoci** [comment]
Yes, you are right! After updating Xcode everything works fine now! Thank you again!
