### ISSUE TITLE
Merge-Queue rerunning CI

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#1386]
Not sure if it is by design, but the merge queue currently runs most of CI twice, even if no other PR was merged since the last CI run, which ~doubles the time till an approved PR is merged into main.
Is there something we can do about this @tgymnich ? I did not find anything here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue

**Comment by wsmoses** [comment]
Going to close this here since I'm not sure it's something we can fix on our end.
