### ISSUE TITLE
issues with override

### ISSUE THREAD

**Issue by ryanelandt** [EnzymeAD/Enzyme#1455]
I think there's some issue relating to calling Enzyme functions that call methods that `override`. Functions that call methods that are `final` are okay. MWE is below.

```c++
int enzyme_dupnoneed;
template < typename return_type, typename ... T >
return_type __enzyme_autodiff(void*, T ... );

/////

class B {
public:
  virtual double get_offset() const = 0;  // Pure virtual method
};

class D : public B {
public:
  // Gives runtime error saying:
  //   Attempting to call an indirect active function whose runtime value is inactive
  double get_offset() const override { return 1.0; }

  // // Runs fine
  // double get_offset() const final { return 1.0; }
};


template <class Block>
double calc_cost(Block& block) {
  return block.get_offset();
}


int main() {
  const auto d = D();
  auto d_dup = D();
  __enzyme_autodiff<double>(
    (void*)calc_cost<D>,
    enzyme_dupnoneed, &d, &d_dup
  );
};
```

**Comment by wsmoses** [comment]
Ah so sorry for the delay.

In these instances, you need to also create a shadow vtable for the shadow argument, which therefore contains the corresponding derivatives of virutal (and thus overridden) functions. See here for a version of your code which does so:
https://fwd.gymni.ch/jBOYa6 . 

In the future, feel free to ping me / others if we don't respond promptly or feel free to join our weekly meeting!
