### ISSUE TITLE
Adding an advanced option flag with Enzyme CMake

### ISSUE THREAD

**Issue by gaurav-arya** [EnzymeAD/Enzyme#1471]
I'm using Enzyme's CMake template (https://github.com/EnzymeAD/CMake-Template/blob/main/CMakeLists.txt) and I'm not sure how to add advanced options like `loose-type-analysis` that are mentioned in the docs: https://enzyme.mit.edu/getting_started/UsingEnzyme/. I'd appreciate any help, thanks!

**Comment by tgymnich** [comment]
I haven’t tried myself. But maybe something like `add_link_options(-mllvm -your-flag)` in case you are using LLDEnzyme. Or `add_compile_options(-mllvm -your-flag)` for ClangEnzyme

**Comment by wsmoses** [comment]
Resolved by adding extra parameters to Enzyme exported cmake
