### ISSUE TITLE
Performed illegal update analysis on Kalman example

### ISSUE THREAD

**Issue by gaurav-arya** [EnzymeAD/Enzyme#1491]
Error output: https://gist.github.com/gaurav-arya/5fa4ee593c1d5c8adb20dca44823bcd2

To reproduce, run cmake on https://github.com/ZuseZ4/kalman/pull/3/commits/6c3e78da2bd17c7d30495286ce112dab628f6123 and then execute `example_robot1`

The error does not occur for small matrix size `n`, but does for `n` around 10 or larger

**Comment by ZuseZ4** [comment]
@wsmoses this is priority over #1490

**Comment by wsmoses** [comment]
https://fwd.gymni.ch/9xgpZs

**Comment by wsmoses** [comment]
https://fwd.gymni.ch/QIad2r

**Comment by wsmoses** [comment]
https://fwd.gymni.ch/WKQeuc

**Comment by wsmoses** [comment]
So it looks like loop unrolling causes this to go from legal to illegal: https://godbolt.org/z/7j8v1crTj

https://fwd.gymni.ch/AeZM0m

**Comment by wsmoses** [comment]
Unroll reduction: https://godbolt.org/z/1MfWMqGbb and https://fwd.gymni.ch/Gom8by

**Comment by wsmoses** [comment]
More reduction: https://godbolt.org/z/KfoWGGdW6 and https://fwd.gymni.ch/LPHNfm

**Comment by wsmoses** [comment]
More reduction: https://godbolt.org/z/d7v1Mvde8 and https://fwd.gymni.ch/h73SUd

**Comment by wsmoses** [comment]
Continuing: https://godbolt.org/z/3cbjnEbox and https://fwd.gymni.ch/gxz3VE

**Comment by wsmoses** [comment]
More: https://godbolt.org/z/K9zj5K8zT and https://fwd.gymni.ch/QBAOuN

**Comment by wsmoses** [comment]
Fixed by https://github.com/EnzymeAD/Enzyme/pull/1500 and https://github.com/EnzymeAD/Enzyme/pull/1499
