### ISSUE TITLE
The llvm::Type::getInt8PtrTy API is removed in LLVM.

### ISSUE THREAD

**Issue by hokein** [EnzymeAD/Enzyme#1533]
The deprecated `llvm::Type::getInt8PtrTy` is removed in LLVM trunk now (https://github.com/llvm/llvm-project/commit/7b9d73c2f90c0ed8497339a16fc39785349d9610). 

We should replace them to the `llvm::PointerType::getUnqual()`.

**Comment by wsmoses** [comment]
Should be fixed by this PR: https://github.com/EnzymeAD/Enzyme/pull/1534
