### ISSUE TITLE
Support for x86_fp80 (long double)

### ISSUE THREAD

**Issue by maxaehle** [EnzymeAD/Enzyme#1600]
I'm wondering if Enzyme can handle the 80-bit x87 extended precision floating-point format known as `x86_fp80` in LLVM IR, which is used by Clang (and GCC) to represent the C/C++ type `long double`.

From https://fwd.gymni.ch/tpmWJm, I presume that it is not supported right now.

Support for `x86_fp80` could be desirable at some point in the future, because even if users avoid `long double` in their C++ source code, this type can appear in C++ standard library headers included from their source code. For example, libstdc++ uses `long double` to implement [`std::generate_canonical`](https://en.cppreference.com/w/cpp/numeric/random/generate_canonical), if I understand [this code](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libstdc%2B%2B-v3/include/bits/random.tcc;h=7f4bf5ea1836e6540aa92f38ca6562bef41f6e1d;hb=HEAD#l3354) correctly. I suspect that this is also the reason why https://fwd.gymni.ch/HHKrZj fails.

**Comment by wsmoses** [comment]
Yeah this would be good to add (and test). Would you be interested in
looking into this?

The location that Type Analysis assertion is thrown would be a good start.

**Comment by maxaehle** [comment]
Yes, I'll look into this.
