### ISSUE TITLE
Bugreport for complex codebase (probably some math problem)

### ISSUE THREAD

**Issue by FROL256** [EnzymeAD/Enzyme#1613]
Greetings! 
I have a project on differential rendering (path tracer) which uses Enzyme. 

While working with it I encounter some Enzyme bugs and i'm not sure how to report them correctly.
The problem is that i can't reproduce bug on simple code base, and simplifying the complex code base didn't helped me too -- it arises in different places related to math functions.

I have put files from clang bug report to this archive 
https://drive.google.com/file/d/1NbskYqtnwYr1u4n_sppsGNw-Q8YVkrhy/view?usp=sharing 

The buggy branch of my project is here 
https://github.com/Ray-Tracing-Systems/HydraCore3/tree/ad_bug

It has a build instruction, but probably you will need to change some path related to clang and enzyme there ... 

The problem arises on call  gltfEval->FrDielectricPBRT
Inside FrDielectricPBRT different instructions are lead to bug, however the same function in separate project works 
https://github.com/FROL256/enzyme_autodiff_examples

Suppose there is some problems with std::sqrt call because code complies if i remove them.
Please let me know if i could do something to make bug-report useful if it is not in that state currently)
Tnanks!

**Comment by FROL256** [comment]
i have tested both release version and from main branch

**Comment by FROL256** [comment]
The txt file with message is also in the archive on google disk https://drive.google.com/file/d/1NbskYqtnwYr1u4n_sppsGNw-Q8YVkrhy/view?usp=sharing

Its definitely compile time

**Comment by wsmoses** [comment]
@FROL256 I tried setting up your repo to debug, but it looks like it wasn't committed to the repo?

```
wmoses@beast:~/git/Enzyme/enzyme/build17/HydraCore3/build (ad_bug) $ cmake ..
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Debug is OFF!
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done (1.0s)
CMake Error at CMakeLists.txt:182 (add_executable):
  Cannot find source file:

    external/LiteScene/pugixml.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:182 (add_executable):
  No SOURCES given to target: hydra
  ```

**Comment by FROL256** [comment]
srry, forgot about that:

git submodule init
git submodule update

**Comment by wsmoses** [comment]
@FROL256 so I retried your codebase on the lastest main and it appears to compile successfully.

I don't have the file you need but otherwise it seems fine?
```
wmoses@beast:~/git/Enzyme/enzyme/build17/HydraCore3/build (ad_bug) $ LD_LIBRARY_PATH="/home/wmoses/llvms/llvm16/buildD/lib" /home/wmoses/git/Enzyme/enzyme/build17/HydraCore3/bin-release/hydra --help
[drmain]: loading xml ... ../resources/HydraCore/hydra_app/tests/test_42/statex_00001.xml
HydraScene ERROR: Error loading scene from: ../resources/HydraCore/hydra_app/tests/test_42/statex_00001.xml
HydraScene ERROR: File was not found
```

**Comment by FROL256** [comment]
Yep, this is because i have disable all materials except Lambert in main branch. Please consider those two branches:
* ad_bug
* ad_bug_simpler

**Comment by wsmoses** [comment]
So I am on the `ad_bug` branch (my terminal shows the branch before the `$` token).

Specifically I was on
```
wmoses@beast:~/git/Enzyme/enzyme/build17/HydraCore3 (ad_bug) $ git log
commit 8c31bec340c39920ad69e82d0f781a35fccfd54c (HEAD -> ad_bug, origin/ad_bug)
Author: Vladimir Frolov <vladimir.frolov@graphics.cs.msu.ru>
Date:   Wed Jan 17 16:25:56 2024 +0300

    for enzyme bugreport

commit 445148007c9cd5b51a1af9fb8b566f7957ca2fc7
Author: Vladimir Frolov <vladimir.frolov@graphics.cs.msu.ru>
Date:   Wed Jan 17 14:50:16 2024 +0300

    edit

commit 9303979a2b10f48eeb0fb823effffebee7808f9d
Author: Vladimir Frolov <vladimir.frolov@graphics.cs.msu.ru>
```

**Comment by FROL256** [comment]
Ok, so i have made some updates. It seems enzyme_101 AD behaves much better.
But still have a problem in compile time. 
Currently it is "Illegal orIn: Integer right: Float@float PointerIntSame=0"
I didn't yet figured out what exacly gives me this error.

Here is the full way to reproduce the bug from scratch:

1) clone 
* git clone --recursive -b ad_bug3 https://github.com/Ray-Tracing-Systems/HydraCore3.git

2) Please verify you have set correct path in Cmake to enzyme .so
* set(ENZYME_PLUGIN_DLL "/home/frol/PROG/enzyme_101/build/Enzyme/ClangEnzyme-${CLANG_VERSION}.so")

3) Build (please enzure you have enabled Enzyme in project via '-DUSE_ENZYME=ON')
* cd HydraCore3
* mkdir build && cd build
* export CC=/usr/bin/clang-17
* export CXX=/usr/bin/clang++-17
* cmake -DCMAKE_BUILD_TYPE=Release -DUSE_ENZYME=ON -DCLANG_VERSION=17 ..
* make -j 10 

4) Here is the output:

Illegal orIn: Integer right: Float@float PointerIntSame=0
clang++-17: /home/frol/PROG/enzyme_101/Enzyme/TypeAnalysis/../TypeAnalysis/ConcreteType.h:241: bool ConcreteType::orIn(ConcreteType, bool): Assertion `0 && "Performed illegal ConcreteType::orIn"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/bin/clang++-17 -DUSE_ENZYME -D_CRT_SECURE_NO_WARNINGS -I/home/frol/PROG/test_enzyme_bug/HydraCore3 -I/home/frol/PROG/test_enzyme_bug/HydraCore3/external -I/home/frol/PROG/test_enzyme_bug/HydraCore3/external/vkutils -I/home/frol/PROG/test_enzyme_bug/HydraCore3/external/CrossRT -isystem /home/frol/PROG/test_enzyme_bug/HydraCore3/external/tinyexr -isystem /home/frol/PROG/test_enzyme_bug/HydraCore3/external/volk -isystem /home/frol/PROG/test_enzyme_bug/HydraCore3/external/LiteMath -O3 -DNDEBUG "-fopenmp=libomp " -fplugin=/home/frol/PROG/enzyme_101/build/Enzyme/ClangEnzyme-17.so -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wcast-align -Wunused -Woverloaded-virtual -Wconversion -Wno-sign-conversion -Wno-useless-cast -Wno-unused-parameter -Wno-unknown-attributes -Wnull-dereference -Wdouble-promotion -Wformat=2 -fopenmp=libomp -MD -MT CMakeFiles/hydra.dir/diff_render/integrator_dr.cpp.o -MF CMakeFiles/hydra.dir/diff_render/integrator_dr.cpp.o.d -o CMakeFiles/hydra.dir/diff_render/integrator_dr.cpp.o -c /home/frol/PROG/test_enzyme_bug/HydraCore3/diff_render/integrator_dr.cpp
1.	<eof> parser at end of file
2.	Optimizer
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM-17.so.1    0x00007f5915acc406 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 54
1  libLLVM-17.so.1    0x00007f5915aca5b0 llvm::sys::RunSignalHandlers() + 80
2  libLLVM-17.so.1    0x00007f5915a20d70
3  libc.so.6          0x00007f5914642520
4  libc.so.6          0x00007f59146969fc pthread_kill + 300
5  libc.so.6          0x00007f5914642476 raise + 22
6  libc.so.6          0x00007f59146287f3 abort + 211
7  libc.so.6          0x00007f591462871b
8  libc.so.6          0x00007f5914639e96
9  ClangEnzyme-17.so  0x00007f5911bce9cb ConcreteType::orIn(ConcreteType, bool) + 367
10 ClangEnzyme-17.so  0x00007f591207b320 TypeResults::intType(unsigned long, llvm::Value*, bool, bool) const + 716
11 ClangEnzyme-17.so  0x00007f5911e73c4b AdjointGenerator::visitBinaryOperator(llvm::BinaryOperator&) + 301
12 ClangEnzyme-17.so  0x00007f5911ebf1ff llvm::InstVisitor<AdjointGenerator, void>::visitOr(llvm::BinaryOperator&) + 39
13 ClangEnzyme-17.so  0x00007f5911eb136b llvm::InstVisitor<AdjointGenerator, void>::visit(llvm::Instruction&) + 793
14 ClangEnzyme-17.so  0x00007f5911e9faa7 llvm::InstVisitor<AdjointGenerator, void>::visit(llvm::Instruction*) + 39
15 ClangEnzyme-17.so  0x00007f5911e4c500 EnzymeLogic::CreateAugmentedPrimal(RequestContext, llvm::Function*, DIFFE_TYPE, llvm::ArrayRef<DIFFE_TYPE>, TypeAnalysis&, bool, bool, FnTypeInfo const&, std::vector<bool, std::allocator<bool>>, bool, unsigned int, bool, bool) + 21696
16 ClangEnzyme-17.so  0x00007f5911e89436 AdjointGenerator::recursivelyHandleSubfunction(llvm::CallInst&, llvm::Function*, std::vector<bool, std::allocator<bool>> const&, bool, DIFFE_TYPE, bool) + 15320
17 ClangEnzyme-17.so  0x00007f5911e90c98 AdjointGenerator::visitCallInst(llvm::CallInst&) + 10886
18 ClangEnzyme-17.so  0x00007f5911ecd025 llvm::InstVisitor<AdjointGenerator, void>::delegateCallInst(llvm::CallInst&) + 505
19 ClangEnzyme-17.so  0x00007f5911ebf66d llvm::InstVisitor<AdjointGenerator, void>::visitCall(llvm::CallInst&) + 39
20 ClangEnzyme-17.so  0x00007f5911eb15f3 llvm::InstVisitor<AdjointGenerator, void>::visit(llvm::Instruction&) + 1441
21 ClangEnzyme-17.so  0x00007f5911e9faa7 llvm::InstVisitor<AdjointGenerator, void>::visit(llvm::Instruction*) + 39
22 ClangEnzyme-17.so  0x00007f5911e4c500 EnzymeLogic::CreateAugmentedPrimal(RequestContext, llvm::Function*, DIFFE_TYPE, llvm::ArrayRef<DIFFE_TYPE>, TypeAnalysis&, bool, bool, FnTypeInfo const&, std::vector<bool, std::allocator<bool>>, bool, unsigned int, bool, bool) + 21696
23 ClangEnzyme-17.so  0x00007f5911e89436 AdjointGenerator::recursivelyHandleSubfunction(llvm::CallInst&, llvm::Function*, std::vector<bool, std::allocator<bool>> const&, bool, DIFFE_TYPE, bool) + 15320
24 ClangEnzyme-17.so  0x00007f5911e90c98 AdjointGenerator::visitCallInst(llvm::CallInst&) + 10886
25 ClangEnzyme-17.so  0x00007f5911ecd025 llvm::InstVisitor<AdjointGenerator, void>::delegateCallInst(llvm::CallInst&) + 505
26 ClangEnzyme-17.so  0x00007f5911ebf66d llvm::InstVisitor<AdjointGenerator, void>::visitCall(llvm::CallInst&) + 39
27 ClangEnzyme-17.so  0x00007f5911eb15f3 llvm::InstVisitor<AdjointGenerator, void>::visit(llvm::Instruction&) + 1441
28 ClangEnzyme-17.so  0x00007f5911e9faa7 llvm::InstVisitor<AdjointGenerator, void>::visit(llvm::Instruction*) + 39
29 ClangEnzyme-17.so  0x00007f5911e4c500 EnzymeLogic::CreateAugmentedPrimal(RequestContext, llvm::Function*, DIFFE_TYPE, llvm::ArrayRef<DIFFE_TYPE>, TypeAnalysis&, bool, bool, FnTypeInfo const&, std::vector<bool, std::allocator<bool>>, bool, unsigned int, bool, bool) + 21696
30 ClangEnzyme-17.so  0x00007f5911e89436 AdjointGenerator::recursivelyHandleSubfunction(llvm::CallInst&, llvm::Function*, std::vector<bool, std::allocator<bool>> const&, bool, DIFFE_TYPE, bool) + 15320
31 ClangEnzyme-17.so  0x00007f5911e90c98 AdjointGenerator::visitCallInst(llvm::CallInst&) + 10886
32 ClangEnzyme-17.so  0x00007f5911ecd025 llvm::InstVisitor<AdjointGenerator, void>::delegateCallInst(llvm::CallInst&) + 505
33 ClangEnzyme-17.so  0x00007f5911ebf66d llvm::InstVisitor<AdjointGenerator, void>::visitCall(llvm::CallInst&) + 39
34 ClangEnzyme-17.so  0x00007f5911eb15f3 llvm::InstVisitor<AdjointGenerator, void>::visit(llvm::Instruction&) + 1441
35 ClangEnzyme-17.so  0x00007f5911e9faa7 llvm::InstVisitor<AdjointGenerator, void>::visit(llvm::Instruction*) + 39
36 ClangEnzyme-17.so  0x00007f5911e59346 EnzymeLogic::CreatePrimalAndGradient(RequestContext, ReverseCacheKey const&&, TypeAnalysis&, AugmentedReturn const*, bool) + 19912
37 ClangEnzyme-17.so  0x00007f5911ddb2a2
38 ClangEnzyme-17.so  0x00007f5911ddcea4
39 ClangEnzyme-17.so  0x00007f5911de189f
40 ClangEnzyme-17.so  0x00007f5911de3172
41 ClangEnzyme-17.so  0x00007f5911deb5a6 EnzymeNewPM::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 62
42 ClangEnzyme-17.so  0x00007f5911e3178f llvm::detail::PassModel<llvm::Module, EnzymeNewPM, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 71
43 libLLVM-17.so.1    0x00007f5915c3f224 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 276
44 libclang-cpp.so.17 0x00007f591dfe9a25
45 libclang-cpp.so.17 0x00007f591dfe2b28 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) + 6648
46 libclang-cpp.so.17 0x00007f591e36b98e
47 libclang-cpp.so.17 0x00007f591ed91e4c clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) + 44
48 libclang-cpp.so.17 0x00007f591d037816 clang::ParseAST(clang::Sema&, bool, bool) + 614
49 libclang-cpp.so.17 0x00007f591ed570c5 clang::FrontendAction::Execute() + 85
50 libclang-cpp.so.17 0x00007f591ecd26c4 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 708
51 libclang-cpp.so.17 0x00007f591edd0e84 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 660
52 clang++-17         0x00005617a52e6856 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 2454
53 clang++-17         0x00005617a52e43c5
54 libclang-cpp.so.17 0x00007f591e994c59
55 libLLVM-17.so.1    0x00007f5915a20b0c llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 140
56 libclang-cpp.so.17 0x00007f591e99449e clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const + 366
57 libclang-cpp.so.17 0x00007f591e95d40d clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const + 877
58 libclang-cpp.so.17 0x00007f591e95d66e clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const + 142
59 libclang-cpp.so.17 0x00007f591e9791ed clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) + 349
60 clang++-17         0x00005617a52e3d2d clang_main(int, char**, llvm::ToolContext const&) + 11229
61 clang++-17         0x00005617a52f0562 main + 50
62 libc.so.6          0x00007f5914629d90
63 libc.so.6          0x00007f5914629e40 __libc_start_main + 128
64 clang++-17         0x00005617a52e0df5 _start + 37
clang++-17: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Ubuntu clang version 17.0.6 (++20231209124227+6009708b4367-1~exp1~20231209124336.77)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang++-17: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++-17: note: diagnostic msg: /tmp/integrator_dr-11c34a.cpp
clang++-17: note: diagnostic msg: /tmp/integrator_dr-11c34a.sh
clang++-17: note: diagnostic msg: 

********************
make[2]: *** [CMakeFiles/hydra.dir/build.make:90: CMakeFiles/hydra.dir/diff_render/integrator_dr.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:129: CMakeFiles/hydra.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by FROL256** [comment]
If there is something in my code which is unsupported and cause 'Illegal orIn: Integer right: Float@float PointerIntSame=0', could you please give me and advice what i have to seek for. I'll try to remove it.  Thanks!

**Comment by FROL256** [comment]
@wsmoses , do you have any ideas about 'Illegal orIn: Integer right: Float@float PointerIntSame=0' ? ) thx )

**Comment by FROL256** [comment]
I have finally restructured my code by making less nesting and less in-out parameters, and on v103 it works.
