### ISSUE TITLE
Compiling shared object?

### ISSUE THREAD

**Issue by davidedelvento** [EnzymeAD/Enzyme#1658]
I am trying to create a shared object using Enzyme, compiling my code with

```sh
clang -fuse-ld=lld -flto *.o  -o libSomething.so -lm -lgsl -lgslcblas -lomp -Wl,--load-pass-plugin=/path/to/LLDEnzyme-16.so -shared
```

Without Enzyme, everything works fine, but when trying to add Enzyme, the library uses the symbol `__enzime_autodiff` (I can see it with `nm`) and hence fails at runtime with undefined symbol. 
If I compile something very similar to an executable, the problem does not occur.

What might be the cause of this problem?

This is on Linux, LLVM v16.0.2 and Enzyme v0.0.86

Thanks!

**Comment by wsmoses** [comment]
I think you’re missing the fuse-ld=lld

**Comment by davidedelvento** [comment]
> I think you’re missing the fuse-ld=lld

Thank you, I appreciate you taking the time for the feedback. Actually that option is right there in the command line (first argument to `clang`), and the first thing I checked and triple-checked :smile: before posting this issue

I played a little bit with both the one failing to work (even adding a main and attempting to compile as an executable rather than a library) and with the other similar one that works. Here is what I've found:

* adding a main to this one and compiling without `--shared` does not work and in fact it fails with `ld.ldd: error: undefined symbol: __enzime_autodiff`
* compiling the similar one as a shared object rather than an executable works fine and `nm` confirms that the binary does not have a used, but undefined symbol: `__enzime_autodiff`

I came to the conclusion that it must be something related to the other libraries I am linking against. I *thought* that the code I am trying to autodiffing was not invoking `gsl` but perhaps it does. Am I correct that if I want to autodiff some code that invokes a library Enzyme needs to "see" the code from said library? Am I also correct that if the code I am autodiffing does not invoke another library (e.g. BLAS in this example), even thought that other library is still used by other non-autodiffed parts of my code, I can leave that BLAS alone? Or does Enzyme need to "see" that one too?

Assuming that said speculation is correct, is it sufficient for me to compile `gsl` from source with Enzyme as a shared object, or do I need to include its source code in the project and link against its object files, to correctly perform the interprocedural optimization which becomes the gradient computation?

Thanks!

**Comment by wsmoses** [comment]
Ah you're right my apologies.

So that linking error indicates that Enzyme was never run, which in this
case means that LLD needs to run LTO on it.

What is the result of the file command on the .O's

Id hope it says the file is llvm but code. If not whatever compiled those
files presumably did not have LTO on

**Comment by davidedelvento** [comment]
Apologies? No need to, thanks for taking the time to help me instead! As usual, you are right: my Makefile contained a bug and some `*.o` were compiled without `-flto`. I fixed that and the problem became

`Failed to load passes from '/path/to/LLDEnzyme-16.so'. Request ignored.`

It turned out, my `/path/to/` contained a `~` because I had stuff installed in my home directory and apparently LLVM does not dereference `~` but uses it verbatim. Changing that to absolute path fixed that issue too (I am posting this here just for Google to index that in case others have the same problem).

Enzyme is now complaining about the type of primal arguments, but that should be some other trivial mistake I must have made and I can deal with it on my own.

So this ticket can be closed. Just one last question. Do you think it's worth mentioning either or both of these issues on the documentation? Not sure how "frequent" they are, but I can make another PR to add both questions and their answers to https://enzyme.mit.edu/getting_started/Faq/

Have a great weekend!

**Comment by wsmoses** [comment]
Oh yeah more docs is certainly appreciated!

**Comment by davidedelvento** [comment]
PR created to document these facts
