### ISSUE TITLE
comparing unsigned to -2

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#1682]
https://github.com/EnzymeAD/Enzyme/blob/bd36baefd93d1a42f31f0ae0f8d4df1165188289/enzyme/Enzyme/AdjointGenerator.h#L6144

While rebuilding I just noticed this warning - based on GCC 9.4.0 idx seems to be unsigned (and the getIndex function at the top also seems to return an unsigned). Not sure what's the original intention, so just creating an issue.

**Comment by wsmoses** [comment]
So this is an intentional sentinal, that we should probably change to a large unsigned value.

Specifically this value is used if there's an error in the indexing, such that the rest of compilation will succeed (and still have that error print, but not assertion internally).
