### ISSUE TITLE
Error sparsifying an icmp

### ISSUE THREAD

**Issue by martinjm97** [EnzymeAD/Enzyme#1692]
Running `enzyme HEAD-304e21b`

Code:
https://github.com/martinjm97/sparse_deriv_enzyme/blob/main/harness/eigenanalysis.cpp

Full output:
https://pastebin.com/4yA52yXA

Error
```
 No sparsification: not sparse solvable(icmp):   %145 = icmp ne i64 %23, %13 via ({0,+,-1}<nw><%12> + %23)
```

**Comment by wsmoses** [comment]
@martinjm97 I don't see the relevant code, can you upload to enzyme explorer (enzyme.mit.edu/explorer)

**Comment by wsmoses** [comment]
ah I see, the code is not the same as in the CI test harness

e.g. see https://github.com/martinjm97/sparse_deriv_enzyme/blob/0650345099790f8ac4e3471de1d7330c543fd9b5/eigenanalysis/eigen_analysis.cpp#L75

vs
https://github.com/EnzymeAD/Enzyme/blob/c199e36cf3cb7db48a425fdfb2b351013b0db4af/enzyme/test/Integration/Sparse/matrix.h#L138

Can you just use the version from CI (e.g. https://github.com/EnzymeAD/Enzyme/blob/main/enzyme/test/Integration/Sparse/eigen_analysis.cpp) which should have the relevant setup / code, and then add the harness onto it?

**Comment by martinjm97** [comment]
Sorry, the code I'm referring to isn't: https://github.com/martinjm97/sparse_deriv_enzyme/blob/0650345099790f8ac4e3471de1d7330c543fd9b5/eigenanalysis/eigen_analysis.cpp#L75

It's https://github.com/martinjm97/sparse_deriv_enzyme/blob/main/harness/eigenanalysis.cpp. Does the link not work for you?

**Comment by wsmoses** [comment]
So I don't see any autodiff call in that file? Nor any todense

**Comment by martinjm97** [comment]
Sorry, just edited! I realized I was on main instead of `cpp-viz`. The link should now be correct.

**Comment by martinjm97** [comment]
Do you see it here: https://github.com/martinjm97/sparse_deriv_enzyme/blob/cpp-viz/harness/eigenanalysis.cpp.

**Comment by wsmoses** [comment]
Yeah so there's still indirect indexing there via faces (https://github.com/martinjm97/sparse_deriv_enzyme/blob/bba6af8b79d7aa34bd6deceb32f775a884a2c5a2/harness/eigenanalysis.cpp#L103)

**Comment by martinjm97** [comment]
That the same as in https://github.com/EnzymeAD/Enzyme/blob/c199e36cf3cb7db48a425fdfb2b351013b0db4af/enzyme/test/Integration/Sparse/eigen_analysis.cpp#L110

I think it's okay because we don't differentiate wrt that part of the computation.

**Comment by wsmoses** [comment]
I mean I think that's what it is yelling about. We can extend it to add support for that [and be conservative and assume it is always the worst case condition].

**Comment by martinjm97** [comment]
It's weird that it's working in CI, but not in the version in harness. 

I'll can try again from scratch and see if there's some mistake that popped in somewhere.

**Comment by wsmoses** [comment]
The CI one does a different L vs M, and the one in CI had the affine-ification, the other didn't

**Comment by martinjm97** [comment]
Yeah. You're right. I'll revert and debug.

**Comment by wsmoses** [comment]
@martinjm97 this PR https://github.com/EnzymeAD/Enzyme/pull/1712 tells Enzyme to act conservative on non-affine things which hopefully fixes your issue here (aka hopefully having the effect of saying non-differentiable vars can be non-affine)
