### ISSUE TITLE
check-enzyme requires that LLVM_EXTERNAL_LIT is explicitly set 

### ISSUE THREAD

**Issue by andriluka** [EnzymeAD/Enzyme#170]
Hi,

I have been following the "Getting started" [instructions](https://enzyme.mit.edu/Installation) and noticed that one needs to explicitly specify the path to LLVM_EXTERNAL_LIT when calling cmake. 

I think this line in the instructions: 
cmake -G Ninja .. -DLLVM_DIR=/path/to/llvm/lib/cmake/llvm

should probably be:
cmake -G Ninja .. -DLLVM_DIR=/path/to/llvm/lib/cmake/llvm -DLLVM_EXTERNAL_LIT=/path/to/llvm/lib/cmake/llvm/bin/llvm-lit

Otherwise the test check-enzyme later will fail with an error: 

[0/1] Running enzyme regression tests
/bin/sh: line 1: <MY_BUILD_DIR>: Is a directory

Best,
Misha

**Comment by andriluka** [comment]
hmm... just noticed that this issue is already described in the end of the doc :) 

In my case I am rebuilding LLVM from source, but the issue still happens, so it seems it is not specific to Ubuntu's LLVM

**Comment by tgymnich** [comment]
we should auto detect lit now
