### ISSUE TITLE
Many failures when running ninja check-enzyme

### ISSUE THREAD

**Issue by davidedelvento** [EnzymeAD/Enzyme#1763]
Since I am getting unexpected issues when using Enzyme in my project, I decided to verify the installation per the documentation, with first step running `ninja check-enzyme`. 
Running `ninja check-enzyme` fails in 2 seconds with 300 passed tests, 9 expected failures and 571 failures.

Most of the errors are `CHECK: expected string not found in input`, and I've seen also a couple of complains about missing shadow arguments (but I definitely did not real all 500+ of them). This is with the most recent commit in the main branch, namely 638ac37a037. Am I doing something wrong or are the test not supposing to be passing at the moment?

PS: in case it matters: I've got a few issues getting to run the tests, because of `llvm-lit` and `FileCheck` but I think I solved them correctly. I simply added the path where both `llvm-lit` and `FileCheck` were in my installation-from-source of LLVM (v17.0.6) and I also had to install `lit.py`, which I did from PyPI (also at v17.0.6) into a basically empty venv (created with python v3.11.2)

**Comment by wsmoses** [comment]
What issues are you having (besides check-enzyme). The check-enzyme tests are presently expected to fail due to opaque pointers being used in LLVM17+ and needing to be migrated, however all the integration tests should work (and pass CI).
