### ISSUE TITLE
EnzymeCreateForwardDiff missing from CApi.h

### ISSUE THREAD

**Issue by martinjrobins** [EnzymeAD/Enzyme#1923]
I'm implementing a compiler in rust for a small DSL (https://github.com/martinjrobins/diffsl), and am using enzyme to implement autodiff on the generated LLVM IR. 

I'm using enzyme's C api and generating rust bindings from `CApi.h`, and in particular I'd like to use `EnzymeCreateForwardDiff`, however its declaration is missing from `CApi.h`. Is there a particular reason for this, and would you accept a PR to add this to `CApi.h`?

**Comment by wsmoses** [comment]
Oh yeah go for it!
