### ISSUE TITLE
Unexpected Compiler Error in Rust Enzyme Bindings for Forward Autodiff

### ISSUE THREAD

**Issue by g-bauer** [EnzymeAD/Enzyme#2047]
I was playing around with the Rust bindings for Enzyme and encountered an unexpected issue (see [here](https://github.com/EnzymeAD/rust/issues/174)). I created two functions with the same signature, doing the same thing. One of them allocates an intermediate `Vec` (see below), the other does not. The latter works as expected, while the other one yields a compiler error. I am not sure if the allocation is the issue here?

Here's the code that crashes, copied from the issue:
```rust
#![feature(autodiff)]
#[autodiff(df2f, Forward, Const, Dual, Dual)]
#[no_mangle]
pub fn _f2(x: &[f64], y: f64) -> f64 {
    let xy: Vec<_> = x.iter().map(|xi| xi / y).collect();
    xy.iter().sum()
}

fn main() {
    df2f(&[1.0], 1.0, 1.0);
}
```
The error message is:
```

rustc: /code/rust/src/llvm-project/llvm/lib/IR/Instructions.cpp:686: void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, const llvm::Twine&): Assertion `(Args.size() == FTy->getNumParams() || (FTy->isVarArg() && Args.size() > FTy->getNumParams())) && "Calling a function with bad signature!"' failed.
```

Following the debug instructions for the Rust bindings, I created LLVM IR's and pasted them into the Enzyme Explorer - which yielded the same error. [Here](https://fwd.gymni.ch/GKr8Uy) is the un-reduced output, [this](https://fwd.gymni.ch/SufoUf) is the reduced one.

Sadly, I am not proficient in reading these IR's to figure out what's going on here that causes the crash.

**Comment by ZuseZ4** [comment]
Looks good, thanks for reporting. 
@ Billy, if you click at the Rust issue link you'll see that he has another working example with the same number, types, and activities of arguments. So I think this isn't due to a bug in my Rust frontend. Lmk if you have questions on the Rust side.

**Comment by wsmoses** [comment]
Can you paste the error message to the issue to make sure it’s preserved in
the history?

**Comment by wsmoses** [comment]
Should be fixed by https://github.com/EnzymeAD/Enzyme/pull/2055

**Comment by ZuseZ4** [comment]
I updated the Enzyme submodule, please lmk if the error persists:
https://github.com/EnzymeAD/rust/pull/176
