### ISSUE TITLE
Use of CMake Presets

### ISSUE THREAD

**Issue by MattBolitho** [EnzymeAD/Enzyme#2162]
I was wondering if consideration had been given to the use of [CMake Presets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html). They improve a few aspects of the CMake experience like editor integration and sharing prefab configurations which users can extend with their own custom setups. For instance, I think it could be useful for #1607,  where it seems like MSVC specific configurations would be useful.

For some demonstration, I have [a branch in my fork](https://github.com/MattBolitho/Enzyme/tree/cmake-presets) where they work to a basic extent with parity with the current configuration options from the Enzyme root CMake project. It needs some tidying, but hopefully it is illustrative enough of the general ideas.

**Comment by wsmoses** [comment]
I've never used it before, but go for it!
