### ISSUE TITLE
Flags from docs nonexisting?

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#2186]
https://enzyme.mit.edu/getting_started/UsingEnzyme/#cache-behavior

Both of these flags seem to be non-existing? I tried to use them due to Enzyme allocating over 100GB before getting killed. I wasn't able to get the flag to work (others flags did work). I also tried to grep the flags in the Enzyme codebase, also without success.

**Comment by wsmoses** [comment]
Yeah they used to exist, but I think they were since removed when we switched over to more advanced caching algorithms via mincut/etc
