### ISSUE TITLE
Chunked forward mode

### ISSUE THREAD

**Issue by vchuravy** [EnzymeAD/Enzyme#260]
After we have preliminary support for forward mode, we might need to think about doing chunking.

@ChrisRackauckas had some references around challenges.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/PreallocationTools.jl shows some of the challenges. 

```julia
function foo(du, u, (A, tmp), t)
    mul!(tmp, A, u)
    @. du = u + tmp
    nothing
end
```

uses `tmp` as a cache, but if you forward-mode AD on it, the cache is the wrong size. So you need some way to create cache to match the shadow memory size, allow the user to create a cache which knows this information, and have it swap in when differentiation. With ForwardDiff we can do this via dispatch:

```julia
using LinearAlgebra, OrdinaryDiffEq, PreallocationTools
function foo(du, u, (A, tmp), t)
    tmp = get_tmp(tmp, u)
    mul!(tmp, A, u)
    @. du = u + tmp
    nothing
end
chunk_size = 5
prob = ODEProblem(foo, ones(5, 5), (0., 1.0), (ones(5,5), dualcache(zeros(5,5), Val{chunk_size})))
solve(prob, TRBDF2(chunk_size=chunk_size))
```

`dualcache` creates the Float64 and Dual versions, and `get_tmp` grabs the cache vector depending on the type of `u`. To create a fully non-allocating forward mode function, this kind of handling of pre-allocated global caches with hooks to the AD will be needed.

**Comment by wsmoses** [comment]
Before considering an allocating work around, I'm inclined to start by thinking of what an analysis that detects if the forward mode can be successfully batched/vectorized would be.

I'd imagine that a primitive first use would be, upon a section of code that can't be batched, to make an implicit for around that for all inputs, and perhaps given a sufficiently good analysis this should push the batching/chunking/vectorization as deep as possible.

**Comment by vchuravy** [comment]
@jrevels i think in ForwardDiff.jl it is specialized upon, right? I.e. that would be set as an compile time paramenter

**Comment by ChrisRackauckas** [comment]
Yes, in ForwardDiff it's a compile time parameter. That makes sense for ForwardDiff because it acts scalar-by-scalar and needs to know the tuple size to make the generated code non-allocating. I think that Enzyme would similarly want to be generating non-allocating code?
