### ISSUE TITLE
Segfault on libCEED with unrolling disabled

### ISSUE THREAD

**Issue by wsmoses** [EnzymeAD/Enzyme#367]
https://github.com/CEED/libCEED/blob/leila/enzyme-ad/examples/solids/qfunctions/finite-strain-neo-hookean-initial-1-ad.h

```
$ cd ~/git/Enzyme/enzyme/sc/libCEED/examples/solids 
$ export PETSC_DIR=/mnt/pci4/wmdata/Enzyme/enzyme/sc/libCEED/petsc
$ export PETSC_ARCH=arch-linux-c-debug
$ export ENZYME_LIB=$HOME/git/Enzyme/enzyme/build12/Enzyme/ClangEnzyme-12.so
```

cc @jedbrown @LeilaGhaffari

**Comment by LeilaGhaffari** [comment]
After introducing `enzyme_nofree` I haven't been able to free the allocated memory as before. For the sake of simplicity, I created a [test](https://github.com/LeilaGhaffari/my-enzyme/blob/main/tests/test014.c) that has all the pieces we need in libCEED. The following is the output of valgrind:
```
$ valgrind --leak-check=full --track-origins=yes ./a.out 
==136838== Memcheck, a memory error detector
==136838== HEAP SUMMARY:
==136838==     in use at exit: 48 bytes in 2 blocks
==136838==   total heap usage: 3 allocs, 1 frees, 1,072 bytes allocated
==136838== 
==136838== 48 bytes in 2 blocks are definitely lost in loss record 1 of 1
==136838==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==136838==    by 0x401331: main (in /home/leila/git/my-enzyme/tests/a.out)
==136838== 
==136838== LEAK SUMMARY:
==136838==    definitely lost: 48 bytes in 2 blocks
==136838==    indirectly lost: 0 bytes in 0 blocks
==136838==      possibly lost: 0 bytes in 0 blocks
==136838==    still reachable: 0 bytes in 0 blocks
==136838==         suppressed: 0 bytes in 0 blocks
==136838== 
==136838== For lists of detected and suppressed errors, rerun with: -s
==136838== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```
I see a similar error in libCEED. Are there any extra steps I need to take to free `tape`?

**Comment by wsmoses** [comment]
For now, I think the easiest thing to do is before you call free, to call enzyme_reverse, but without the nofree (explicitly causing a free).

We should probably add an enzyme_free that just free's without also computing a derivative as well.

**Comment by LeilaGhaffari** [comment]
Thanks! Calling `__enzyme_reverse()` before calling `free()` did help. `enzyme_free()` looks like a great idea though!
