### ISSUE TITLE
LLDEnzyme

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#540]
Right now we have ClangEnzyme and LLVMEnzyme.
For cases where we use Enzyme as a linker Plugin during LTO we might want to add an extra LLDEnzyme for a slightly nicer integration instead of using ClangEnzyme.

**Comment by zhenxl** [comment]
I'm now diving into lld, and i'm interested in this project, how should i start?

**Comment by ZuseZ4** [comment]
Hi @zhenxl, so it turned out to be an issue for a few of us, so it was just fixed, since it was only a minor Cmake change.
However, if you are interested to look into lld, we might have a more interesting (yet to create) issue. 
Right now we run full lto, which is nice for the additional performance gains, but has some serious compile-time impact.
It would be really nice to optionally only use thin lto. 
I don't know if it will require updates to lld, but if you already want to look into lld that would surely come handy.
Feel free to create a new issue if you are interested. Also, we have weekly meetings (see https://groups.google.com/g/enzyme-dev), so please feel free to also join there!
