### ISSUE TITLE
Differentiating a vector valued function

### ISSUE THREAD

**Issue by ipcamit** [EnzymeAD/Enzyme#576]
Hi, I am bit unclear on how to use enzyme for a function that accepts two arrays and save the result of operations on first array into the second one (f(vec) -> vec). Given below is my toy attempt:

```C++
#include <cmath>
#include <iostream>

void vec_func(double * x, double * result){
    result[0] = std::pow(x[0],2) + std::pow(x[1],3);
    result[1] = x[0] + x[1];
}

void __enzyme_autodiff(void (*) (double *, double *), 
                            /*duplicated argument*/ double * , double *,
                            double *);

int main(){
    double x[2] = {0.0};
    double result[2] = {0.0};
    double grad_x[2] = {0.0};
    x[0] = 2.0; x[1] = 3.0;

    __enzyme_autodiff(vec_func, x, grad_x, result);
    return 0;
}
```
I get the following error and warning when I try to compile it:

```
$ opt input.ll -load=/opt/enzyme/enzyme/build/Enzyme/LLVMEnzyme-12.so -enzyme  -o output.ll -S
warning: <unknown>:0:0: __enzyme_autodiff missing argument shadow at index 4, need shadow of type double* to shadow primal argument   %10 = getelementptr inbounds [2 x double], [2 x double]* %2, i64 0, i64 0 at call   call void @_Z17__enzyme_autodiffPFvPdS_ES_S_S_(void (double*, double*)* nonnull @_Z8vec_funcPdS_, double* nonnull %7, double* nonnull %9, double* nonnull %10)
error: <unknown>:0:0: EnzymeFailure when replacing __enzyme_autodiff calls in main
```

Can anyone please help me with a correct implementation of the above? 

If I interpret it correctly it is complaining regarding the shadow argument for `result` array? I tried `/*output argument*/` but still got same error. So I am not sure.

**Comment by wsmoses** [comment]
You also need to provide a shadow output variable, like below:
```
#include <cmath>
#include <iostream>

void vec_func(double * x, double * result){
    result[0] = std::pow(x[0],2) + std::pow(x[1],3);
    result[1] = x[0] + x[1];
}

void __enzyme_autodiff(void (*) (double *, double *), ...);

int main(){
    double x[2] = {0.0};
    double result[2] = {0.0};
    double grad_x[2] = {0.0};
    x[0] = 2.0; x[1] = 3.0;

    double d_x[2] = {2.0, 3.0};

    __enzyme_autodiff(vec_func, x, grad_x, result, d_x);
    return 0;
}
```

In the above example you'll compute 2.0 * the gradient of result[0] + 3.0 * the gradient of result[0]. If you want the gradient of just one output, you can use a one-hot encoding (e.g. set all zero except the result you care about). And indeed this generalizes to give you a linear sum of all the gradients, multiplied with the corresponding shadow.

Also as a note, if you're using Clang, there's an easier way to call this (no need for separate opt, no vectorization/unroll flags, etc):

```
clang++ input.cpp -Xclang -load -Xclang /path/to/ClangEnzyme-XX.so -O3
```

Note that if you use LLVM >= 13 you may need to add an extra flag (see: https://enzyme.mit.edu/getting_started/Faq/#opt-cant-find--enzyme-option )

**Comment by ipcamit** [comment]
When I compile the example you provided, I get following linker error:

```
/usr/bin/ld: /tmp/core-af6ff5.o: in function `main':
core.cpp:(.text+0x92): undefined reference to `__enzyme_autodiff(void (*)(double*, double*), ...)'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```
Clang version 12
Command:
```
 clang++ input.cpp -Xclang -load -Xclang /opt/enzyme/enzyme/build/Enzyme/LLVMEnzyme-12.so -O3  -v
```
My git log states I last pulled Enzyme on 25 Jan, was this functionality added after that, do I need to rebuild enzyme?

On related side note, is there any detailed enzyme documentation? I was excitedly waiting for more fleshed out examples and details after the Feb 6 documentation hackathon announced on the google group, but enzyme.mit.edu still shows old documentation page.

**Comment by tgymnich** [comment]
You need to use `ClangEnzyme-12.so` instead of` LLVMEnzyme-12.so`.

```
clang++ input.cpp -Xclang -load -Xclang /opt/enzyme/enzyme/build/Enzyme/ClangEnzyme-12.so -O3  -v
```
