### ISSUE TITLE
 undefined symbol: enzyme_dupnoneed

### ISSUE THREAD

**Issue by fbartolic** [EnzymeAD/Enzyme#587]
I'm trying to build a C++ project which uses enzyme and expose it to Python via `pybind11`. Here is a  hopefully reproducible example: https://github.com/fbartolic/enzyme_cmake

On my machine, compiling `cpu_ops.cc` with  `clang++ cpu_ops.cc -Xclang -load -Xclang /home/fb90/opt/Enzyme/enzyme/build/Enzyme/ClangEnzyme-13.so -O2 -flegacy-pass-manager -std=c++14 $(python3 -m pybind11 --includes) -o integrate_image_cpu_op$(python3-config --extension-suffix) --gcc-toolchain="/share/apps/gcc112/" -shared -fPIC` gives me a  cpython library which I can import in python without issues. 

However, whe using cmake I get the following error when importing the module into Python:
```
ImportError: /home/fb90/projects/enzyme_cmake/build/integrate_image_cpu_op.cpython-39-x86_64-linux-gnu.so: undefined symbol: enzyme_dupnoneed
```
I don't know cmake very well so I just tried to adapt the example in https://github.com/EnzymeAD/CMake-Template to get this to work. Does anyone know what's going on here?

**Comment by wsmoses** [comment]
As you're using LLVM 13 or above you need to add the flag `-fno-experimental-new-pass-manager` or `-flegacy-pass-manager` (see https://enzyme.mit.edu/getting_started/Faq/#opt-cant-find--enzyme-option).

**Comment by fbartolic** [comment]
But I am using the flag `-fno-experimental-new-pass-manager` in `CMakeLists.txt`.

**Comment by wsmoses** [comment]
Can you place the flag before the load to Enzyme?

**Comment by fbartolic** [comment]
It is before the load to Enzyme currently if I'm not missing something: https://github.com/fbartolic/enzyme_cmake/blob/main/CMakeLists.txt

**Comment by wsmoses** [comment]
Ah I see the problem, in your cmake you're not loading Enzyme as a C++ lib. 

Try changing:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-experimental-new-pass-manager -fuse-ld=lld -flto --gcc-toolchain=/share/apps/gcc112/ -lstdc++")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-experimental-new-pass-manager -fuse-ld=lld -flto")
set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld -flto -Wl,-mllvm=-load=${ClangEnzyme}")
set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld -flto -Wl,-mllvm=-load=${ClangEnzyme}")
```
to
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-experimental-new-pass-manager -Xclang -load -Xclang ${ClangEnzyme}")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-experimental-new-pass-manager -Xclang -load -Xclang ${ClangEnzyme}")
```

**Comment by fbartolic** [comment]
That works although I'm getting the following warning:
```
freeing without malloc   %call2 = call noalias nonnull i8* @_Znam(i64 %8) #24
freeing without malloc   %call = call noalias nonnull i8* @_Znam(i64 %3) #24
freeing without malloc   %call2 = call noalias nonnull i8* @_Znam(i64 %8) #24
freeing without malloc   %call = call noalias nonnull i8* @_Znam(i64 %3) #24
```

**Comment by wsmoses** [comment]
That's a warning that should (usually) be fine to ignore about memory allocation behavior. Assuming your code here is similar to the other issue, any problems arising from are being looked into in the background.

**Comment by fbartolic** [comment]
Awesome, thanks for the help!

**Comment by wsmoses** [comment]
@tgymnich can you update the docs on the cmake template to make clear how it can be used. This shows that someone looking at it might be misled.
