### ISSUE TITLE
How does one request Enzyme to specifically use Forward Mode or Reverse Mode?

### ISSUE THREAD

**Issue by Nirhar** [EnzymeAD/Enzyme#617]
Hi everyone! 
I'm new to Enzyme and would like to know if Enzyme gives the user the option of choosing between forward mode and Reverse mode for AD. I couldn't find any code pertaining to it in the [User Manual Webpage](https://enzyme.mit.edu/getting_started/CallingConvention/), and it would be great if you could direct me to some code examples that show how one can choose between the 2 modes.

**Comment by wsmoses** [comment]
Forward mode isn’t documented yet, but here is an example of how to use (and several more are in that same directory).

https://github.com/EnzymeAD/Enzyme/blob/main/enzyme/test/Integration/ForwardMode/binops.c

**Comment by Nirhar** [comment]
Thanks!
