### ISSUE TITLE
Incorrect/Non-existent Gradients when Differentiating Octree

### ISSUE THREAD

**Issue by ludgerpaehler** [EnzymeAD/Enzyme#642]
Hey everyone,

When attempting to differentiate through modifications made to an Octree, in the style of Enzyme's "Getting Started" guide there are quite a few issues where Enzyme either fails to recognise a change, or is completely off with the derivative..

## Case 1: No (zero) gradient at all

Operation: x^2

https://fwd.gymni.ch/Hx46Zx

## Case 2: Wrong gradient

Operation: 4 * x^2, with a random initialisation of the initial octree

https://fwd.gymni.ch/fpmV8A

In addition we are hitting constraints within, I suppose, Enzyme, where it does not want to peek deep into the Octree, e.g.

```bash
not handling more than 6 pointer lookups deep dt:{[]:Pointer, [0]:Pointer, [0,0]:Pointer, [0,0,0]:Pointer, [0,0,0,0]:Pointer, [0,0,0,0,0]:Pointer, [0,0,0,0,0,0]:Pointer, [0,0,0,16]:Float@double, [0,0,16]:Float@double} only(-1): {[]:Pointer, [0]:Pointer, [0,0]:Pointer, [0,0,0]:Pointer, [0,0,0,0]:Pointer, [0,0,0,0,0]:Pointer, [0,0,0,0,0,0]:Pointer, [0,0,0,16]:Float@double, [0,0,16]:Float@double}
```

All of these issues are encapsulated in the two compiler-explorer examples above.

**Comment by tgymnich** [comment]
Version of Case 2 without hash map: https://fwd.gymni.ch/8Vm0sa

**Comment by wsmoses** [comment]
Version two actually looks correct to me.

You define for all elemnts `elem = 4 * elem^2`. This means the derivative is `8 * elem delem`. Since you initialize delem and elem to be the same thing, you get `delem = 8 * orig(elem)^2`, which is what I see.

**Comment by wsmoses** [comment]
The same applies to your original program. Setting all initializers to 1 rather than to 0, you get 2 x as desired.

```
Gradient Tree
Print tree
    Level 0
        ID 3
        6 6 6 6 6 
        ID 2
        4 4 4 4 4 
        ID 1
        2 2 2 2 2 
        ID 0
        0 0 0 0 0 
    Level 1
        ID 5
        10 10 10 10 10 
        ID 4
        8 8 8 8 8 
```
