### ISSUE TITLE
f != originalToNewFn.end()

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#657]
I have a library which crashes when using Enzyme. After the IO updates it now failes at the following assertion:
`f != originalToNewFn.end()`

I have the errormessage / stacktrace here
[err.txt](https://github.com/EnzymeAD/Enzyme/files/8712129/err.txt)

Is there anything obviously wrong around this assertion?
I will work on providing a minimized src code example.

Also, how would I pass the extra enzyme-print flags, when using LLDEnzyme?

**Comment by wsmoses** [comment]
```
i8* inttoptr (i64 152 to i8*)
ld.lld: /home/drehwald/prog/Rust/src/tools/enzyme/enzyme/Enzyme/GradientUtils.h:474: llvm::Value* GradientUtils::getNewFromOriginal(const llvm::Value*) const: Assertion `f != originalToNewFn.end()'
```

The issue is inside invertPointerM:

For a constexpr it may not be in the map if not used directly, clearly this is a constant value, and if it is such a constantexpr, we should just return it and no need to do the originalToNew.

Want to take a stab at it (and yes please add a minimal test)?

**Comment by ZuseZ4** [comment]
Sounds doable, I will try it tomorrow and ping you if I get stuck.

**Comment by ZuseZ4** [comment]
After the last two PRs and setting globals to inactive, I'm now hitting the following assertion:
`number of arg operands != function parameters`
[err.txt](https://github.com/EnzymeAD/Enzyme/files/8721761/err.txt)

Is there anything specific wrong around AdjointGenerator.h line 11166?
