### ISSUE TITLE
compile time: 7s -> 60 minutes

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#686]
I do have a trivial but huge program which takes 7s to compile using clang-14.04 with -O3 and lto for the normal pass.
using __enzyme_autodiff together with -O3 and lto increases the compile time by a factor of over 500.
The algorithm takes 10 entries with values given at runtime and updates the next 30k entries one by one based on 1-5 previous entries. Each line is super trivial, similar to:
`v[12345] = v[37] + v[123] * v[2];`
The final vector is used with some weights for a dot-product.

The access patterns and update rules are all given at compile time, only the first few entries change during runtime.

Since LLVM limits the size of each compilation unit, I group those update rules into sub-functions, each of which updates 500 entries.

The compile time seems to scale almost perfectly linear with the length of the vector, so no quadratic behaviour, but rather a huge overhead.
I will add a simplified python script to generate arbitrary large testcases after lunch.

**Comment by wsmoses** [comment]
@ZuseZ4 can you upload the code that triggers this into the issue? If not this will be hard to track, fix, etc.

**Comment by ZuseZ4** [comment]
Yes, will try today
