### ISSUE TITLE
Support Opaque Pointers

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#687]
Motivated by https://discourse.llvm.org/t/cast-x-is-broken-implications-and-proposal-to-address/63033
I just build enzyme on top of llvm-head. Enzyme would compile fine and ninja check-enzyme only has 6 extra tests failing (on top of the old 6 ones). However enzyme-check-integration for me fails almost all tests:
```
Testing Time: 0.62s
  Passed           :  3
  Expectedly Failed:  4
  Failed           : 87
```
llvm-14 integration test work fine (except of those where I'm missing the deps).

Edit, my bad. I missed the opaque pointers have been switched on by default for 15, that's causing 67 of the failures.

**Comment by ZuseZ4** [comment]
@tgymnich Do you have a few minutes to verify if it's only a local issue on my side?

**Comment by wsmoses** [comment]
Yeah opaque pointer support is the likely cause here. Feel free to take a stab at it!

**Comment by ZuseZ4** [comment]
https://discourse.llvm.org/t/rfc-better-support-for-typed-pointers-in-an-opaque-pointer-world/63339/3
