### ISSUE TITLE
unable to use Enzyme on multi-source program on MacOS

### ISSUE THREAD

**Issue by haianyt** [EnzymeAD/Enzyme#710]
Hi,
I am working on a multi-source project that uses Enzyme to do the autodiff. I found it hard to make the compilation work on MacOS. Below is the code example, the Makefile is similar to #648 . The code worked on Linux but failed on MacOS. It seems that Mac uses the ld64.lld by default, which causes the issue. I wonder if you can give me some hints on fixing it. Thanks!

```cpp
// main.cpp
#include "square.h"
#include <iostream>

int main()
{
    double x = 3.0;
    printf("square(%f)=%f\n", x, square(x));
    printf("dsquare(%f)=%f\n", x, dsquare(x));
    return 0;
}
```
```cpp
// square.h
#pragma once

double square(double x);
double dsquare(double x);
```
```cpp
// square.cpp
#include "square.h"
extern double __enzyme_autodiff(void *, double)__attribute__((weak));
double square(double x)
{
    return x * x;
}

double dsquare(double x)
{
    return __enzyme_autodiff((void*)square, x);
}
```
`Makefile`:
```Makefile
main: main.o square.o
	clang++ -flto -o main main.o square.o

main2: main.o square.o
	clang++ -fuse-ld=lld -flto -o main2 main.o square.o -Wl,--lto-legacy-pass-manager -Wl,-mllvm=-load=/usr/local/lib/LLDEnzyme-13.dylib

main.o: main.cpp
	clang++ -flto -c main.cpp

square.o: square.cpp
	clang++ -flto -c square.cpp

clean:
	rm -f main main.o square square.o main2*
```
`Error message` after calling `make main2`:
```
clang++ -fuse-ld=lld -flto -o main2 main.o square.o -Wl,--lto-legacy-pass-manager -Wl,-mllvm=-load=/usr/local/lib/LLDEnzyme-13.dylib
ld64.lld: error: unknown argument '-mllvm=-load=/usr/local/lib/LLDEnzyme-13.dylib'
ld64.lld: error: undefined symbol: __enzyme_autodiff(void*, double)
>>> referenced by square.o
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by elite-sheep** [comment]
I think you may run the optimization pass with the following command:
```
${CC} square.cpp -flto -O0 -Xclang -load -Xclang /usr/local/lib/ClangEnzyme-12.dylib -S -o square.bc
```

And then you may link square.bc with main.bc

**Comment by haianyt** [comment]
I think ClangEnzyme-13.dylib is only used for single source file. I need to use Enzyme on multiple files which requires LLDEnzyme-13.dylib.

**Comment by ZuseZ4** [comment]
Unfortunately I can't help with Apple, but what you could try for the meantime is compiling your files into llvm-ir (.ll or .bc) without invoking Enzyme and use llvm-link to merge those into a single file. Afterwards you should be able to run ClangEnzyme.
It's slightly more complex which is why most people use LTO, however I've used this setup somewhat successfully with multiple rust crates / compilation units. 

As a side note, I would recommend to run at least -O0 (afaik better O1). This makes sure that at least a minimal set of passes will be run. Depending on your actual code this might be necessary for Enzyme.

**Comment by wsmoses** [comment]
`-O0` is what's run by defauly if you don't have a flag, and yes I would highly recommend using at least O1.

Can you paste the results of clang --version, and for lld as well. Also are you using Apple clang, homebrew, or something else.

Finally what version of macOS?

**Comment by haianyt** [comment]
Add the -O1 flag doesn't seem to make a difference.
Here is my clang version:
`clang --version`:
```
Homebrew clang version 13.0.1
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

`ld64.lld --version`:

```
Homebrew LLD 13.0.1
```
I installed the llvm using homebrew. My macOS version is 12.4 and it's an M1 mac.

**Comment by haianyt** [comment]
I'm trying to integrate Enzyme into a CMake project. Using llvm-link can work on Mac. But In CMake, the linker is generally invoked by clang. It's a bit hard to manually call the linker unless we implement some custom commands and targets.

**Comment by btalamini** [comment]
Try changing your link line to this:
```
clang++ -fuse-ld=lld -flto -o main2 main.o square.o -Wl,--lto-legacy-pass-manager -Wl,-mllvm -load=/usr/local/lib/LLDEnzyme-13.dylib
```
(note the removed `=` between `-mllvm` and `-load`)

On my Mac, I can build your `main2` target successfully with this. I don't know why the module loading syntax is different on MacOS.

**Comment by haianyt** [comment]
This worked on my Mac as well. Thanks @btalamini for the solution!

**Comment by btalamini** [comment]
Cool.  @wsmoses, I think this can be closed.

**Comment by ipcamit** [comment]
@btalamini , Hi do you have any idea on how to convert your suggestion to CMake on Mac OS? In linux my CMakefile has the following section
```
# pass linking to lld, with enzyme plugin
if (${LLVM_MAJOR_VERSION} LESS_EQUAL 13)
    target_link_options(descriptor PRIVATE "LINKER:--lto-legacy-pass-manager")
    target_link_options(descriptor PRIVATE "LINKER:-mllvm=-load=${ENZYME_LIB}/LLDEnzyme-${LLVM_MAJOR_VERSION}.so")
     target_link_options(descriptor PRIVATE "LINKER:-mllvm=-enzyme-loose-types")
else()
    target_link_options(descriptor PRIVATE "LINKER:--load-pass-plugin=${ENZYME_LIB}/LLDEnzyme-${LLVM_MAJOR_VERSION}.so")
endif()
```
But it did not work on Mac OS, and it keeps on complaining that --lto-legacy-pass-manager is not a valid argument

**Comment by ipcamit** [comment]
@btalamini Do you know how to pass `-enzyme-loose-types` in Makefiles for mac? Whatever I try, it splits the `-enzyme-loose-types` as `-e nzyme-loose-types` and ignores it.:

```
Stack dump:
0.	Program arguments: /opt/homebrew/Cellar/llvm@13/13.0.1_2/bin/ld64.lld -demangle -dynamic -arch arm64 -platform_version macos 14.0.0 14.0.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -e nzyme-loose-types -o bin/libdescriptor.dylib obj/Bispectrum.o obj/Descriptors.o obj/SOAP.o obj/SymmetryFunctions.o obj/Xi.o obj/helper.o obj/maths/bessel_functions.o obj/maths/clebsh_gordon.o obj/maths/gamma.o obj/maths/gl_quad.o obj/maths/precomputed_bessel_zeros.o obj/maths/radial_basis_functions.o obj/maths/spherical_harmonics.o --lto-legacy-pass-manager -e nzyme-loose-types -mllvm -load=/usr/local/lib/LLDEnzyme-13.dylib -lc++ -lSystem /opt/homebrew/Cellar/llvm@13/13.0.1_2/lib/clang/13.0.1/lib/darwin/libclang_rt.osx.a
                                                                                                                                                                                            ----------------------------^This here----------------------------------
```

**Comment by wsmoses** [comment]
lmao out of curiousity, mind pasting the chatgpt log. I'm genuinely curious how much it knows how to use Enzyme

**Comment by ipcamit** [comment]
Sure, it was about general linker query and not enzyme,
Query:
```
I am trying to invoke a flag at link time in Mac, but it keeps taking the linker flag and splitting it up, example:

 -Wl,-mllvm -enzyme-loose-types
ld64.lld: error: cannot open nzyme-loose-types: No such file or directory
ld64.lld: error: -mllvm: lld: Unknown command line argument '-e'.  Try: 'lld --help'
```

ChatGPT replied:

This error usually happens because the `-Wl` flag is not being passed correctly to the linker, leading to it interpreting the `-mllvm` flag incorrectly. When you pass linker flags using `-Wl`, you need to ensure that the entire flag string is enclosed correctly so that the linker treats it as a single argument.

Here are a few ways you can pass the `-mllvm -enzyme-loose-types` flag correctly to the linker:
Using `-Xlinker`

One approach is to use `-Xlinker` to pass options directly to the linker. For example:

```sh
clang ... -Xlinker -mllvm -Xlinker -enzyme-loose-types ...
```

Using `-Wl`

Alternatively, you can use `-Wl` but ensure that the entire flag string is treated as a single argument:

```sh
clang ... -Wl,-mllvm,-enzyme-loose-types ...
```

Using Escaping for Single Arguments

Ensure that each part of the `-mllvm` argument is properly quoted or escaped:

```sh
clang ... -Wl,-mllvm,-enzyme-loose-types ...
```

Full Example

Let's assume you're compiling a source file main.c. Here are both methods in full context:

Using `-Xlinker`:

```sh
clang main.c -o main -Xlinker -mllvm -Xlinker -enzyme-loose-types
```

Using -Wl:

```sh
clang main.c -o main -Wl,-mllvm,-enzyme-loose-types
```

Explanation

    `-Xlinker`: This flag tells the compiler to pass the following argument directly to the linker. By using -Xlinker for each part of the -mllvm option, you ensure that they are treated as separate arguments by the linker.

    `-Wl`: This flag tells the compiler to pass the following argument to the linker, treating it as a single string. By separating the components with commas, you ensure that the linker sees them as distinct options.

By using either of these methods, you should be able to pass the `-mllvm -enzyme-loose-types` option correctly to the linker without it being split incorrectly.
