### ISSUE TITLE
Unknown Binary Operator urem

### ISSUE THREAD

**Issue by umatin** [EnzymeAD/Enzyme#727]
In line 70 "%tmp15 = urem i64 %tmp14, 128, !dbg !19" an assertion "cannot handle unknown binary operator:" is triggered in the AdjointGenerator.
When bypassing line 70-71 the code compiles fine.
https://fwd.gymni.ch/pJdCWp

**Comment by wsmoses** [comment]
Reducing: https://fwd.gymni.ch/UHcozV
