### ISSUE TITLE
Enzyme cannot handle Function Bitcast Changing Number of Parameters

### ISSUE THREAD

**Issue by umatin** [EnzymeAD/Enzyme#728]
If a function pointer is cast to a function with fewer arguments, enzyme gets the number of arguments wrong in multiple places.

In line 20 a bitcast causes an out of bounds error "%call = call float* bitcast ({ float*, float*, i64 } (float*, float*, i64, i64, i64, float*, float*, i64, i64, i64)* @kernel_main to float* (float*, float*, i64, i64, i64)*)(float* noundef %0, float* noundef %1, i64 noundef 0, i64 noundef 0, i64 noundef 0)"
 Assertion `i < getNumArgOperands() && "Out of bounds!"' failed.
https://fwd.gymni.ch/Abbx1P

**Comment by wsmoses** [comment]
While I concur that we should have a better error message, in this instance calling a function with too few arguments (in particular not passing a pointer that is dereferenced) will absolutely result in a runtime segfault.

**Comment by tgymnich** [comment]
https://godbolt.org/z/cd81a8dP3

**Comment by wsmoses** [comment]
Oh I'm not saying in general, I mean for this particular code.

In particular in kernel_main `float* %5, float* %6, i64 %7, i64 %8, i64 %9` will all be undefined.

Thus when its loaded from below, it will segfault as loading from an undef pointer:

```
  %16 = insertvalue { float*, float*, i64, [1 x i64], [1 x i64] } undef, float* %5, 0, !dbg !19
  %17 = insertvalue { float*, float*, i64, [1 x i64], [1 x i64] } %16, float* %6, 1, !dbg !20
  %18 = insertvalue { float*, float*, i64, [1 x i64], [1 x i64] } %17, i64 %7, 2, !dbg !21
  %19 = insertvalue { float*, float*, i64, [1 x i64], [1 x i64] } %18, i64 %8, 3, 0, !dbg !22
  %20 = insertvalue { float*, float*, i64, [1 x i64], [1 x i64] } %19, i64 %9, 4, 0, !dbg !23
  
  %40 = extractvalue { float*, float*, i64, [1 x i64], [1 x i64] } %20, 1, !dbg !42
  %41 = getelementptr float, float* %40, i64 %34, !dbg !43
  %42 = load float, float* %41, align 4, !dbg !44
  ```
