### ISSUE TITLE
The calculated derivative shows all ZERO

### ISSUE THREAD

**Issue by rem1A** [EnzymeAD/Enzyme#734]
I know Enzyme takes INT arguments as inactive arguments by default, but so does an array whose elements are also INTEGER?

In a simple test, I tried to use Enzyme to differentiate an INT array, but the result shows all zero, then I changed the type of the array to FLOAT [ ] , the result shows the correct value.

Then I work it on a benchmark, the argument I wanted to differentiate is an INT array, the result shows zero, but even if I changed the type to FLOAT [ ], the result still shows all zero. I don't know why, is that because the array I differentiate represents an INDEX, and Enzyme takes it as INT again?

If in a more complex case, I do not know what is the correct value of the derivative, how can I distinguish WHY is the derivative shows ZERO? Is that because the element I try to differentiate represents an INDEX or the derivative is actually calculated as zero?

**Comment by wsmoses** [comment]
Integer values (whether stand alone, or in an array) are currently assumed to be inactive.

The functionality for active integers can be added, but isn't implemented presently.

Closing this issue as a duplicate of https://github.com/EnzymeAD/Enzyme/issues/158
