### ISSUE TITLE
Enzyme runtime segfault

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#768]
Apparently Tim's update didn't fix all of them @wsmoses. 
When compiling OpenLB while also setting globals-default-inactive, (beside of the mandatory strict-aliasing=0 and relaxing TA) the compilation succeeds (although with likely incorrect gradients). The resulting binary however seems to be corrupted: 

```.s
[XMLreader] Warning: cannot read value from node "XML node not found", "ObjectiveMaterial"
Program received signal SIGSEGV, Segmentation fault.
0x00007efcd6618b00 in std::locale::~locale() () from /lib/x86_64-linux-gnu/libstdc++.so.6
```

Trying std::locale on the compiler explorer did however work for me, I'll see if I can find something to reproduce.

**Comment by wsmoses** [comment]
@ZuseZ4 can you upload the code that triggers this into the issue? If not this will be hard to track, fix, etc.

**Comment by ZuseZ4** [comment]
Too long ago (closed source development, just opensourcing specific releases). I'm not at that University anymore and with Enzyme's multihour compiletimes I can't invest the time to try and reproduce this with one of the published releases, sorry. But I can create a benchmark generator for compiletimes.
