### ISSUE TITLE
Compiler Explorer doesn't recognize @_Znwm()

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#808]
https://fwd.gymni.ch/LnqFW1

**Comment by wsmoses** [comment]
https://fwd.gymni.ch/sSDYu7

**Comment by wsmoses** [comment]
@ZuseZ4 the problem is that the malloc-like function doesn't have an input argument for size.

What's the C++ generator code?

**Comment by ZuseZ4** [comment]
Don't have one. Got it by running llvm-reduce on IR obtained by -print-before=enzyme, when compiling the almost full OprnLB codebase. Maybe llvm-reduce broke it?

**Comment by wsmoses** [comment]
Yeah, unfortunately.
