### ISSUE TITLE
Understanding subindex operation

### ISSUE THREAD

**Issue by arnamoy10** [EnzymeAD/Enzyme#813]
Hello;

I was trying to understand the `polygeist.subindex` operation.  Can anybody please explain why as a result of some subindex operation, we see one of the dimension being removed, in other cases we don't see the dimension being removed?

```
%20 = "polygeist.subindex"(%arg2, %19) : (memref<?xf32>, index) -> memref<?xf32>   <-- dimension kept
%31 = "polygeist.subindex"(%30, %arg12) : (memref<?xf32>, index) -> memref<f32>     <-- dimension removed
```

The lines are taken from `polygeist/test/polygeist-opt/cpuifyloopdistribute.mlir` file

**Comment by wsmoses** [comment]
Closing as dup of https://github.com/llvm/Polygeist/issues/266 [and this is the wrong repo]
