### ISSUE TITLE
Move intrinsic handling from AdjointGenerator.h to Tablegen.

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#843]

**Comment by ZuseZ4** [comment]
https://github.com/EnzymeAD/Enzyme/blob/3dab78c293fd8f70dd696e58ffd18cd00fc0324f/enzyme/Enzyme/AdjointGenerator.h#L4680

**Comment by tgymnich** [comment]
addressed in #1285
