### ISSUE TITLE
website certificate outdated

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#850]
Just in case that you missed it.

Firefox detected an issue and did not continue to enzyme.mit.edu. The website is either misconfigured or your computer clock is set to the wrong time.

It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

**Comment by jedbrown** [comment]
Indeed, certificate expired `Mon, 19 Sep 2022 23:59:59 GMT`.

**Comment by wsmoses** [comment]
I submitted the ticket to MIT to renew (this historically happened automatically, but they've gotten behind on).

**Comment by wsmoses** [comment]
This should now be fixed.
