### ISSUE TITLE
How to properly initialize the argument class to `_enzyme_virtualreverse` 

### ISSUE THREAD

**Issue by ipcamit** [EnzymeAD/Enzyme#891]
I am trying to pass a class with inherited virtual method to  `_enzyme_autodiff`. To do so I first create an empty class object with default constructor then follow instructions at #316 . I can compile the code just fine, however at runtime I get segfault. GDB points to a custom data-structure which might be returning invalid pointer/value
```
Array2D<double>::operator() (this=<optimized out>, i=<optimized out>, j=<optimized out>) at /home/../descriptor-library/./helper.hpp:2066
2066	 return this->m[_n];
(gdb) 
```
But when I try to pass an initialized class to `_enzyme_virualreverse` I get the following error:
```
FAILED: libdescriptor.so 
: && /opt/llvm_12/clang_12_prebuilt/bin/clang++ -fPIC -g -O3 -fuse-ld=lld -flto -O3 -DNDEBUG  -Xlinker --lto-legacy-pass-manager -Xlinker -mllvm=-load=/opt/enzyme/enzyme/build/Enzyme/LLDEnzyme-12.so -shared -Wl,-soname,libdescriptor.so -o libdescriptor.so ... cpp.o   && :
ld.lld: error: Descriptors.cpp:163:40: in function _ZN10Descriptor20gradient_single_atomEiiPiS0_iPdS1_S1_S1_PNS_14DescriptorKindE void (i32, i32, i32*, i32*, i32, double*, double*, double*, double*, %"class.Descriptor::DescriptorKind"*): Enzyme: Cannot create virtual version of non-constant value   %22 = tail call i8* @_Z23__enzyme_virtualreverseIPvET_S1_(i8* %21) #35, !dbg !5331  %21 = load i8*, i8** %20, align 8, !dbg !5329, !tbaa !5330
```

How can I pass an initialized class to `_enzyme_virtualreverse` ?

Enzyme version: 0.0.41
clang:12.1
Compiler and linker flag options:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -O3 -fuse-ld=lld -flto -Xclang -new-struct-path-tbaa")
target_link_options(descriptor PRIVATE "LINKER:--lto-legacy-pass-manager")
target_link_options(descriptor PRIVATE "LINKER:-mllvm=-load=/opt/enzyme/enzyme/build/Enzyme/LLDEnzyme-12.so")

```

**Comment by wsmoses** [comment]
Can you post a minimal example of this?

**Comment by ipcamit** [comment]
Of compilation error from `__enzyme_virtualenv`? Or from the segfaulting? Minimal example of segfault will be difficult, as it is considerably large project with several dependencies :(

**Comment by ipcamit** [comment]
Hi sorry for this issue, I am closing it. I found a workaround. It was because I was initializing some class memeber in default constructor. Instead I wrote a separate function to initialize my class, and called it after the call to `__enzyme_virtualreverse` . It works fine in that case.

**Comment by ipcamit** [comment]
I just wanted one more clarification, the class object that is passed to `__enzyme_reverse`, does its member's values influence the derivatives? Or can I set all of their values to 0.0 and not worry about it?

**Comment by ipcamit** [comment]
Here is a minimal working example : https://fwd.gymni.ch/0FXTSe

Without explicit `-O3` flag it fails to compile

**Comment by wsmoses** [comment]
@ipcamit class variables are like a regular duplicated arg, you should probably set them to 0.0, since in reverse mode the derivative results are +='d into them.
