### ISSUE TITLE
LLVM 14.0.6 crashes while loading enzyme

### ISSUE THREAD

**Issue by jandrej** [EnzymeAD/Enzyme#965]
```
/***/local/bin/clang++ -O3 -std=c++17 -I./../hypre/src/hypre/include -Xclang -load -Xclang /***/local/lib/ClangEnzyme-14.so -flegacy-pass-manager -c general/optparser.cpp -o general/optparser.o -I/***/openmpi/***/include -fexceptions -pthread
```
Here is the log file from `-mllvm -print-before-all` [out.log](https://github.com/EnzymeAD/Enzyme/files/10414033/out.log)

**Comment by tgymnich** [comment]
Enzyme should work on LLVM 14.0.6. 
Have you tried putting `-flegacy-pass-manager` before `-Xclang -load -Xclang /***/local/lib/ClangEnzyme-14.so`.?

**Comment by wsmoses** [comment]
@jandrej can you retry and see if this is now able to be closed?
