### ISSUE TITLE
Enzyme crash in IR

### ISSUE THREAD

**Issue by jandrej** [EnzymeAD/Enzyme#968]
Maybe related to #965?

`ll` file attached and renamed because of github.

[optparser.ll.txt](https://github.com/EnzymeAD/Enzyme/files/10522938/optparser.ll.txt)

**Comment by wsmoses** [comment]
@jandrej @jdoerfert this isn't reproducing in compiler explorer? https://fwd.gymni.ch/Hbu4eQ

**Comment by jandrej** [comment]
@wsmoses can I get a brief explanation on the cause?

**Comment by wsmoses** [comment]
We previously handled global variable for custom derivative and other registration being marked as `llvm.used` (https://llvm.org/docs/LangRef.html#the-llvm-used-global-variable). However, some how (presumably LTO?) this was being marked as `llvm.compiler.used`, which we didn't handle and the above closing PR adds support for (https://llvm.org/docs/LangRef.html#the-llvm-compiler-used-global-variable).
