### ISSUE TITLE
CMake Quality of Life: export targets, `ExternalProject`

### ISSUE THREAD

**Issue by samuelpmish** [EnzymeAD/Enzyme#981]
Hi, I'm just starting to try out enzyme and it's a little bit unclear how to integrate it into an existing C++/CMake project.

After building and installing Enzyme, `find_package` does something, but I can't seem to figure out what it actually defines, or how to use it.

I was hoping that I might be able to follow the idiomatic cmake patterns of doing one of

- (installed Enzyme)
```cmake
find_package(Enzyme REQUIRED)

add_executable(my_application main.cpp)
target_link_libraries(my_application PUBLIC Enzyme::Enzyme)
```

- (Enzyme as a subdirectory)
```cmake
add_subdirectory(path/to/Enzyme)

add_executable(my_application main.cpp)
target_link_libraries(my_application PUBLIC Enzyme::Enzyme)
```

but neither seemed to work. I'm able to define a custom `INTERFACE` target locally, doing 

```cmake
add_library(Enzyme INTERFACE)
set(MY_ENZYME_LIB "/my/specific/hardcoded/path/to/Enzyme/enzyme/build/Enzyme/ClangEnzyme-14.so")
target_compile_options(Enzyme INTERFACE -flegacy-pass-manager)
target_compile_options(Enzyme INTERFACE "SHELL: -Xclang -load")
target_compile_options(Enzyme INTERFACE "SHELL: -Xclang ${MY_ENZYME_LIB}")
# note: the "SHELL: ..." stuff seems to be necessary to stop CMake's flag deduplication
# from removing the second -Xclang flag

add_executable(my_application main.cpp)
target_link_libraries(my_application PUBLIC Enzyme) # works!
```

Would it make sense to include such a target in Enzyme directly, to streamline the user CMake experience? 
Or maybe something like this already exists and I just missed it!

-----------

Another, unrelated thought: the documentation [here](https://enzyme.mit.edu/Installation/) seems a little out of date with respect to supported versions of LLVM. CMake's `ExternalProject_Add` tool would let the Enzyme CMake build grab a vetted version of the llvm repo and automatically configure/build it with the appropriate flags, which would make building from source as simple as

```
git clone https://github.com/EnzymeAD/Enzyme
cd Enzyme/enzyme
cmake . -Bbuild && cmake --build build --parallel
```

And for backward compatiiblity, if a user specified `-DLLVM_DIR=...` then the user-provided directory would be used instead of downloading LLVM through CMake.

**Comment by wsmoses** [comment]
Definitely would be nice to add the cmake interface, would you like to start a PR?

**Comment by tgymnich** [comment]
This looks interesting. [Here](https://github.com/EnzymeAD/CMake-Template) is how `find_package` can be used.

**Comment by samuelpmish** [comment]
update: my original flags for the Enzyme interface target don't work for projects with more than 1 source file, but 

```cmake
add_library(Enzyme INTERFACE)                                                    
set(LLDENZYME_LIB "path/to/Enzyme/enzyme/build/Enzyme/LLDEnzyme-14.so")
target_compile_options(Enzyme INTERFACE -flto)                                   
target_link_options(Enzyme INTERFACE "SHELL: -fuse-ld=lld")                      
target_link_options(Enzyme INTERFACE "SHELL: -Wl,--lto-legacy-pass-manager")
target_link_options(Enzyme INTERFACE "SHELL: -Wl,-mllvm=-load=${LLDENZYME_LIB}")
```

seems to work (except, we should get the LLDENZYME_LIB path from the installation directory rather than hardcoding it)

**Comment by tgymnich** [comment]
You can get `LLDEnzyme` from the CMake package. You also need to make sure, that CMake builds your binaries with the same version of clang/lld (`Enzyme_LLVM_BINARY_DIR` from the CMake package) that Enzyme was built against.

**Comment by wsmoses** [comment]
I think the LTO and Clang variants should be two distinct options that are provided to folks. Maybe EnzymeLTO for first. For the clang variant, I'm not sure what to call it since we already have EnzymeClang as the name of the lib itself. Ideas?

**Comment by wsmoses** [comment]
And CMake should be able to check the compiler version against the one Enzyme used.

**Comment by samuelpmish** [comment]
> You also need to make sure, that CMake builds your binaries with the same version of clang/lld (Enzyme_LLVM_BINARY_DIR from the CMake package) that Enzyme was built against.

is using the same clang/lld necessary (or is it just sufficient) for a build with Enzyme to work?

**Comment by wsmoses** [comment]
Enzyme must be built against an LLVM with a compatible ABI. Effectively this means it must be the same LLVM version and build type (debug etc). Some vendors like AMD don't stick with release LLVM versions so you need to ensure it's the precise same compiler in that case.

**Comment by wsmoses** [comment]
@samuelpmish we now should support LLVM16 per https://github.com/EnzymeAD/Enzyme/pull/1207

**Comment by samuelpmish** [comment]
> we now should support LLVM16

Wonderful, I'm giving it a try now!

----------

Here's the updated test suite results after merging the changes from #1207 on the ubuntu 22.04 machine:

```
running add_subdirectory tests
llvm11: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ✅
llvm12: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ✅
llvm13: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ✅
llvm14: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ✅
llvm15: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ❌
llvm16: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ❌
running find_package tests
llvm11: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ✅
llvm12: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ✅
llvm13: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ✅
llvm14: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ✅
llvm15: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ❌
llvm16: configuring cmake ... ✅ | building ClangEnzyme test ... ✅ | building LLDEnzyme test ... ❌
```

It looks like LLDEnzyme is still having issues with LLVM 15, and LLVM 16 experiences the same problem. Am I passing the shared library to LLD incorrectly here?

```sh
/home/sam/code/llvm/15/build/bin/clang++ -O3 -DNDEBUG -fuse-ld=lld -Wl,-mllvm -Wl,-load-pass-manager=/home/sam/code/Enzyme/fork/enzyme/install/15/lib/LLDEnzyme-15.so CMakeFiles/enzyme_test_2.dir/main.cpp.o -o enzyme_test_2   && :
ld.lld: error: -mllvm: ld.lld: Unknown command line argument '-load-pass-manager=/home/sam/code/Enzyme/fork/enzyme/install/15/lib/LLDEnzyme-15.so'.  Try: '/home/sam/code/llvm/15/build/bin/ld.lld --help'
ld.lld: Did you mean '--msan-and-mask=/home/sam/code/Enzyme/fork/enzyme/install/15/lib/LLDEnzyme-15.so'?
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

```sh
/home/sam/code/llvm/16/build/bin/clang++ -O3 -DNDEBUG -fuse-ld=lld -Wl,-mllvm -Wl,-load-pass-manager=/home/sam/code/Enzyme/fork/enzyme/install/16/lib/LLDEnzyme-16.so CMakeFiles/enzyme_test_2.dir/main.cpp.o -o enzyme_test_2   && :
ld.lld: error: -mllvm: ld.lld: Unknown command line argument '-load-pass-manager=/home/sam/code/Enzyme/fork/enzyme/install/16/lib/LLDEnzyme-16.so'.  Try: '/home/sam/code/llvm/16/build/bin/ld.lld --help'
ld.lld: Did you mean '--msan-and-mask=/home/sam/code/Enzyme/fork/enzyme/install/16/lib/LLDEnzyme-16.so'?
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

I also tried `--load-pass-plugin=<value>` (from the `lld --help` output) instead, but it also complained about `--load-pass-plugin` being an unknown argument.
